$evt:=Form event code:C388

Case of 
	: ($evt=Sur données modifiées:K2:15)
		ARRAY TEXT:C222(TChamps; 0)
		QUERY:C277([STRUCTURE_DATA_DESCENDANTES:53]; [STRUCTURE_DATA_DESCENDANTES:53]NomTable:2=TTables{TTables}; *)
		QUERY:C277([STRUCTURE_DATA_DESCENDANTES:53]; [STRUCTURE_DATA_DESCENDANTES:53]NomChamp:3#"#@")
		DISTINCT VALUES:C339([STRUCTURE_DATA_DESCENDANTES:53]NomChamp:3; TChamps)
		INSERT IN ARRAY:C227(TChamps; 1; 1)
		TChamps{1}:=""
End case 
