//%attributes = {}
ARRAY TEXT:C222($GFONCle; 0)
ARRAY TEXT:C222($GFONNom; 0)
ARRAY TEXT:C222($GFONCode; 0)
ARRAY TEXT:C222($GFONcleDir; 0)
ARRAY DATE:C224($GFONdebut; 0)
ARRAY DATE:C224($GFONfin; 0)

ALL RECORDS:C47([IMPORT_GPT_FONCT:36])
DELETE SELECTION:C66([IMPORT_GPT_FONCT:36])


ConnexionSQL

If (OK=1)
	
	SQL EXECUTE:C820("SELECT CLE_GRPFONC, GROUPEMENT, CODE, CLE_DIRECTION, DEBUT, FIN FROM Pompgserv WHERE CODE != ''"; $GFONCle; $GFONNom; $GFONCode; $GFONcleDir; $GFONdebut; $GFONfin)
	SQL LOAD RECORD:C822(SQL tous les enregistrements:K49:10)
	For ($i; 1; Size of array:C274($GFONCle))
		CREATE RECORD:C68([IMPORT_GPT_FONCT:36])
		[IMPORT_GPT_FONCT:36]cle_grpfonc:2:=$GFONCle{$i}
		[IMPORT_GPT_FONCT:36]libelle:3:=$GFONNom{$i}
		[IMPORT_GPT_FONCT:36]trigramme:4:=$GFONCode{$i}
		[IMPORT_GPT_FONCT:36]cle_direction:5:=$GFONcleDir{$i}
		[IMPORT_GPT_FONCT:36]debut:6:=String:C10($GFONdebut{$i})
		[IMPORT_GPT_FONCT:36]fin:7:=String:C10($GFONfin{$i})
		SAVE RECORD:C53([IMPORT_GPT_FONCT:36])
	End for 
	SQL LOGOUT:C872
	
	QUERY:C277([IMPORT_GPT_FONCT:36]; [IMPORT_GPT_FONCT:36]fin:7#"00/00/00")
	DELETE SELECTION:C66([IMPORT_GPT_FONCT:36])
	
	
End if 

