//%attributes = {}
ALL RECORDS:C47([PAGERS:14])
While (Not:C34(End selection:C36([PAGERS:14])))
	CREATE RECORD:C68([DEPENDANCES_PAGERS_EMETTEURS:15])
	[DEPENDANCES_PAGERS_EMETTEURS:15]id_emetteur:2:=[PAGERS:14]id_appartenance_pager:4+"_1"
	[DEPENDANCES_PAGERS_EMETTEURS:15]id_pager:3:=[PAGERS:14]id_pager:2
	SAVE RECORD:C53([DEPENDANCES_PAGERS_EMETTEURS:15])
	NEXT RECORD:C51([PAGERS:14])
End while 
